### ISSUE TITLE
option to run code directly instead of acessing file

### ISSUE THREAD

**Issue by eeerrrttty** [depsterr/dbrainfuck#1]
For my alg to run, i do need to use brainfuck code directly on brainfuck interpreter:

ex.:

dbrainfuck --[----->+<]>-----.

**Comment by rachelambda** [comment]
I've added this in the latest commit, to run your code from the command line you can now do

```sh
dbrainfuck "<code here>" -a
```

this will run the first argument as code. If you have any other issues or suggestions feel free to express them as well!

**Comment by eeerrrttty** [comment]
depsterr... "dbrainfuck "--[----->+<]>-----." -a
Segmentation fault (core dumped)"

**Comment by rachelambda** [comment]
@eeerrrttty

It works well for me, [here is a screenshot](https://imgur.com/a/pvKa3CB)

Are you sure that you reinstalled the new version?
