### ISSUE TITLE
core dumped

### ISSUE THREAD

**Issue by eeerrrttty** [depsterr/dbrainfuck#2]
dbrainfuck "--[----->+<]>-----." -a
Segmentation fault (core dumped)

**Comment by rachelambda** [comment]
@eeerrrttty

It works well for me, [here is a screenshot](https://imgur.com/a/pvKa3CB)

Are you sure that you reinstalled the new version?

**Comment by eeerrrttty** [comment]
![Screenshot from 2020-03-09 14-30-28](https://user-images.githubusercontent.com/19417947/76245631-9790bd00-6212-11ea-8a54-379f9a937603.png)

**Comment by eeerrrttty** [comment]
the buffer hexadecimal prints differently.

**Comment by eeerrrttty** [comment]
![Screenshot from 2020-03-09 14-31-40](https://user-images.githubusercontent.com/19417947/76245690-b42cf500-6212-11ea-9e40-b47903190274.png)

**Comment by eeerrrttty** [comment]
answer should be 'hi'

**Comment by rachelambda** [comment]
Well according to [this online brainfuck interpreter](https://copy.sh/brainfuck/) and my code the result is the character 'a'. I find it confusing however that it does not print 'a' on your machine. Are you really 100% sure that you are running the latest version?

**Comment by rachelambda** [comment]
Nevermind, you do indeed get the a, I just missed it. The issue then is with your code snippet, not with the interpreter.

The 'a' prints on the same row as your prompt since you didn't also print a newline

**Comment by eeerrrttty** [comment]
really, i remade everything, now it appears to run well

**Comment by eeerrrttty** [comment]
remaked it and now worked! Thanks

**Comment by rachelambda** [comment]
Glad to hear!
