### ISSUE TITLE
brainfuck not exiting from input after loop

### ISSUE THREAD

**Issue by eeerrrttty** [depsterr/dbrainfuck#3]
+[>,]+[<.-]

i can input the values, but i cannot stop it, is it right?!

some compilers on web are running fine.

**Comment by eeerrrttty** [comment]
is input output working well?

corrupted size vs. prev_size

**Comment by rachelambda** [comment]
I have never seen input or output fail, I assume the issue is in how the code is written. You keep on taking input before checking for 0, this would mean it would never reach zero unless you gave it a null byte, which would mean that the loop would never end. Please make sure the issue is not within your code before leaving an issue on Github.

**Comment by eeerrrttty** [comment]
Test this code. I Tried this code on other interpreters and It worked as expected

**Comment by rachelambda** [comment]
Why would the code ever leave the first loop?

**Comment by eeerrrttty** [comment]
Bro, why did this code run in other compilers online naturally ?

Sorry if a made something wrong, i'm trying to make this compiler the best possible as i liked it a lot! 

After i wanna give you a small donation for your effort! :)

**Comment by eeerrrttty** [comment]
many times we do put pre-inputs into brainfuck code.

here is an example:

![Screenshot from 2020-03-13 02-08-15](https://user-images.githubusercontent.com/19417947/76594439-86c09f80-64cf-11ea-966a-e0cabb76f8e6.png)

should your program make 'pre-input' possible? Is that the thing or i'm wrong?

**Comment by eeerrrttty** [comment]
![Screenshot from 2020-03-13 03-08-57](https://user-images.githubusercontent.com/19417947/76597913-03577c00-64d8-11ea-91b5-3fbc6f02e3d4.png)

corrupted size vs. prev_size

**Comment by rachelambda** [comment]
why should the loop ever stop?

**Comment by rachelambda** [comment]
Also, you're not even using the `-a` flag in the screenshot you sent.
